language: node_js
node_js:
  - 8.10.0
deploy:
  provider: npm
  email: npm@nickmeldrum.com
  api_key:
    secure: "V8o3pjyls2Av7tpffdXlRHiPZkff3FtndsBXGl+o7HbeWgWt6I1KM2iHAHdWrHzXPAtJkt1kiR/tCdLxMHIHdcDx6dUsV8+wWc/NcFLrliC5gU3t5EJVGtk6BT2GlX4NS1KYLwzG57cVqVtb/kT3T5HVaMRuLNBQWevd6Y9UYpScFakzfNLV/5lAH0biaTrnRyQh4jyGrMNA8K9djo96XkhidibFoO4+7Shj0u3KbaqDdIBt9/6B+3AGkB1+gsAOz6nTxfPyDylhYig00+7qdTcW+XLl5en7fwOv+I+fHCxn94eVj7lxV8HBXrR/WRgFkWWgSer9bmaf7hiHJHU/cQ2LGE0nm5BrkAJjmqPWA9pJqgGx+z++r93PXIxmHuSNQqcFbeVmntiZwQicMy/VUYqlYE0trIdLhGwZSVVL4XN4bjV1QYsjzz0cQE7DxvvRjygFtNhFd0+HP6DCKCNwbqyewQrCSxC+w4JckfER4BZ+54OUcd6XsQB2vcIuV0QvmdzDsOnJHVUjYAaw7SmjBtO+zQAQdk2NfgLW2nCsE+1R6Aetp10oYf5Y8VOsdzion9/m0fzGBHnOKM1VGTPEYSmRWNmoTe8ESd+0pvgbIy7Cv28C2M8XQ0WfvbrQZJzVtoDlytiNeLXgcB+EFQdA2XFKcJPOHQNBIcW7JQb01s4="
  on:
    branch: master
    tags: true
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
